name: CI
on:
  push:
    branches: [ main ]
jobs:
  gh-pages-deployment:
    runs-on: ubuntu-latest
    container:
      image: brczk/dosbox-x
      options: --cpus 1 --volume ${{github.workspace}}:/repo
    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v3
      - name: 'Build'
        uses: joncloud/dos-build-action@v1
        with:
          run: |
            C:
            CD SRC
            TASM /zi TRON.ASM
            TLINK /v TRON.OBJ
          programs: |
            $/turbo-asm/2.01:C:\TASM
            src:C:\SRC
          conf: |
            [dosbox]
            memsize=256

            [cpu]
            cycles=max
            turbo=true
      - name: 'Bundle creation'
        run: cp src/TRON.EXE . && zip -r bundle.jsdos TRON.EXE .jsdos/ && mv bundle.jsdos web/
      - name: 'Github pages deployment'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web
